In [1]:
#Assignment_11

In [2]:
#Question

'''

Using OpenCV implement a single object tracker. Steps to be implemented:
a) Use a pre-recorded video or your webcam to have a video Capture object.
b) Mark the region of interest (ROI or the object you want to track) using it 
   coordinates in the first frame.
c) Calculate the histogram of the ROI.
d) Iteratively calculate the histogram at each location (using cv2,calcBackProject)
   and then apply mean shift to get the updated location of the ROI.

'''

'\n\nUsing OpenCV implement a single object tracker. Steps to be implemented:\na) Use a pre-recorded video or your webcam to have a video Capture object.\nb) Mark the region of interest (ROI or the object you want to track) using it \n   coordinates in the first frame.\nc) Calculate the histogram of the ROI.\nd) Iteratively calculate the histogram at each location (using cv2,calcBackProject)\n   and then apply mean shift to get the updated location of the ROI.\n\n'

In [3]:
import numpy as np
import cv2

In [4]:
cap = cv2.VideoCapture('mean_shift.webm')

In [5]:
ret, frame = cap.read()

In [6]:
x, y, width, height = 300, 200, 100, 50
track_window = (x, y, width, height)

In [10]:
roi = frame[y:y + height, x:x + width]
print (roi)

[[[131 133 140]
  [131 133 140]
  [131 133 140]
  ...
  [118 120 127]
  [118 120 127]
  [118 120 127]]

 [[131 133 140]
  [131 133 140]
  [131 133 140]
  ...
  [118 120 127]
  [118 120 127]
  [118 120 127]]

 [[131 133 140]
  [131 133 140]
  [131 133 140]
  ...
  [118 120 127]
  [118 120 127]
  [118 120 127]]

 ...

 [[131 133 140]
  [131 133 140]
  [131 133 140]
  ...
  [129 137 146]
  [123 135 147]
  [120 132 144]]

 [[133 133 140]
  [133 133 140]
  [134 134 141]
  ...
  [139 141 143]
  [137 139 146]
  [133 135 142]]

 [[133 133 140]
  [133 133 140]
  [134 134 141]
  ...
  [140 142 144]
  [139 141 148]
  [137 139 146]]]


In [11]:
hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
print (hsv)

[[[  7  16 140]
  [  7  16 140]
  [  7  16 140]
  ...
  [  7  18 127]
  [  7  18 127]
  [  7  18 127]]

 [[  7  16 140]
  [  7  16 140]
  [  7  16 140]
  ...
  [  7  18 127]
  [  7  18 127]
  [  7  18 127]]

 [[  7  16 140]
  [  7  16 140]
  [  7  16 140]
  ...
  [  7  18 127]
  [  7  18 127]
  [  7  18 127]]

 ...

 [[  7  16 140]
  [  7  16 140]
  [  7  16 140]
  ...
  [ 14  30 146]
  [ 15  42 147]
  [ 15  42 144]]

 [[  0  13 140]
  [  0  13 140]
  [  0  13 141]
  ...
  [ 15   7 143]
  [  7  16 146]
  [  7  16 142]]

 [[  0  13 140]
  [  0  13 140]
  [  0  13 141]
  ...
  [ 15   7 144]
  [  7  16 148]
  [  7  16 146]]]


In [9]:
# cv2.imshow('fd', hsv)
#cv2.waitKey(0)

In [13]:
mask = cv2.inRange(hsv, np.array((0., 61., 33.)), np.array((180., 255., 255.)))

In [14]:
roi = cv2.calcHist([hsv], [0], mask, [180], [0, 180])
print (roi)

[[  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  3.]
 [  0.]
 [ 28.]
 [ 80.]
 [162.]
 [192.]
 [ 65.]
 [ 11.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]


In [15]:
# cv2.imshow('fd', roi)
# cv2.waitKey(0)

In [16]:
cv2.normalize(roi, roi, 0, 255, cv2.NORM_MINMAX)

array([[  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  3.984375],
       [  0.      ],
       [ 37.1875  ],
       [106.25    ],
       [215.15625 ],
       [255.      ],
       [ 86.328125],
       [ 14.609375],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0.      ],
       [  0. 

In [17]:
termination = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 1 )

In [18]:
while(True):
    ret, frame = cap.read()
    if ret == True:
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        bp = cv2.calcBackProject([hsv], [0], roi, [0, 180], 1)

        ret, track_window = cv2.meanShift(bp, track_window, termination)
        x, y, width, height = track_window

        final_image = cv2.rectangle(frame, (x, y), (x + width, y + height), 255, 2)
        cv2.imshow('tracker', final_image)

        k = cv2.waitKey(1) & 0xff
        if k == ord('q'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()